---
# Ensure log directory exists
- name: Ensure log directory for Janitor exists
  file:
    path: "{{ os_janitor_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

# Deploy the main janitor script
- name: Deploy OpenStack Janitor script
  template:
    src: "openstack-janitor.sh.j2"
    dest: "{{ os_janitor_script_path }}"
    owner: root
    group: root
    mode: '0755'
  notify: Restart janitor timer
  