---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart janitor timer
  ansible.builtin.systemd:
    name: os-janitor.timer
    state: restarted
    enabled: true
